name: flyer_chat_text_message
version: 3.10.1

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_chat_core: ^3.10.1
  provider: ^6.1.1

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
