name: flyer_chat_image_message
version: 3.10.1

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  cross_file: ^0.3.3+8
  crypto: ^3.0.3
  flutter:
    sdk: flutter
  flutter_chat_core: ^3.10.1
  http: ^1.2.0
  mime: ^1.0.5
  path_provider: ^2.1.2
  provider: ^6.1.1
  thumbhash: ^0.1.0+1

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
